repos:
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        name: black (python)
        language_version: python3

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: 5.11.4
    hooks:
      - id: isort
        name: isort (python)
        language_version: python3

