model:
  num_classes: 20
  num_boxes: 2
  input_size: [224, 224]
  device: null

preprocessing:
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]

postprocessing:
  conf_threshold: 0.5
  iou_threshold: 0.4