MIN_NUM_FACES_AT_FRAME = 1
MAX_NUM_FACES_AT_FRAME = 3
MIN_MAIN_CHAR_IOU = 0.5
MAX_MAIN_CHAR_IOU = 0.75

N_GRAYSCALE_DIMENSIONS = 2

N_SINGLE_CHANNEL = 1
N_BGR_CHANNELS = 3
N_BGRA_CHANNELS = 4

N_MAX_RSPLIT_SPLITS = 1
JPEG_QUALITY_VALUE = 95

MIN_IMAGE_DIMENSION = 100
ALLOWED_NUM_CHANNELS = [1, 3, 4]
MAX_ASPECT_RATIO = 3.0
MIN_IMAGE_BYTE_SIZE = 5000
