name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # This ensures all branches are fetched
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      
      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Lint (black, isort)
        run: |
          black --check .
          isort --check-only .
      
      - name: Ensure test_data directory exists
        run: |
          mkdir -p tests/test_data
      
      - name: Copy annotations file and test images
        run: |
          # Check if we're on a pull request
          if [ -n "${{ github.event.pull_request.number }}" ]; then
            echo "Running in PR context"
            # Copy test_data files directly from main branch
            git checkout origin/main -- tests/test_data/annotations.txt
            git checkout origin/main -- tests/test_data/test1.jpg
            git checkout origin/main -- tests/test_data/test2.jpg
            git checkout origin/main -- tests/sample_avi_video.avi
            git checkout origin/main -- tests/sample_mp4_video.mp4
          else
            echo "Running in push context"
            # We're already on main, so just make sure the files are there
            if [ ! -f "tests/test_data/annotations.txt" ]; then
              echo "Error: annotations.txt not found in current branch"
              exit 1
            fi
          fi
      
      - name: Verify files exist
        run: |
          echo "Checking file existence:"
          ls -la tests/test_data/
          echo "Content of annotations file:"
          cat tests/test_data/annotations.txt || echo "File not found or empty"
      
      - name: Run tests
        run: |
          export PYTHONPATH=$GITHUB_WORKSPACE
          pytest -v
