name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      
      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Lint (black, isort)
        run: |
          black --check .
          isort --check-only .
      
      - name: Create directory structure for test files
        run: |
          mkdir -p tests/test_data
      
      - name: Download test videos and files
        run: |
          wget -r -np -nH --cut-dirs=N https://raw.githubusercontent.com/raodz/BestFrameEver/main/tests/
          
      
      - name: Verify files exist
        run: |
          echo "Files in tests/test_data:"
          ls -la tests/test_data/ || echo "Directory not found"
      
      - name: Run tests
        run: |
          export PYTHONPATH=$GITHUB_WORKSPACE
          pytest -v
