name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Lint (black, isort)
        run: |
          black --check .
          isort --check-only .
      - name: Run tests (pytest)
        run: PYTHONPATH=$GITHUB_WORKSPACE/src pytest
